development:
  default: &default
    default_locale: 'es'
    iso: 'es'
    root: false
    country: 'es'

  'localhost:4000':
    <<: *default
  'localhost:3000':
    <<: *default

test: &development

production:
  default: &default
    default_locale: 'es'
    iso: 'es'
    root: false
    country: 'es'

  'iflowframework.com':
    << *default
  'iflowframework.es':
    << *default
